# Generated by Django 4.1.3 on 2022-11-26 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 12, 39, 28, 485791, tzinfo=datetime.timezone.utc)),
        ),
    ]
